language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t yusushin/yuda -f ./front/Dockerfile.dev ./front

script:
  - docker run -e CI=true yusushin/yuda npm test

after_success:
  - docker build -t yusushin/docker-frontend ./front
  - docker build -t yusushin/docker-backend ./back
  - docker build -t yusushin/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push yusushin/docker-frontend
  - docker push yusushin/docker-backend
  - docker push yusushin/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: 'Yuda'
  env: 'Yuda-env'
  bucket_name: elasticbeanstalk-ap-northeast-2-270304892797
  bucket_path: 'Yuda'
  on:
    branch: Main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY