version: '1'

services:
  frontend:
    # build:
    #   dockerfile: Dockerfile
    #   context: ./front
    image: fronttest.azurecr.io/yudafront

    env_file:
      - front/.env
    # environment:
    #   - REACT_APP_SERVER=${REACT_APP_SERVER}

    volumes:
      - /app/node_modules
      - ./front:/app
      
    stdin_open: true

  backend:
    # build: 
    #   dockerfile: Dockerfile
    #   context: ./back
    image: fronttest.azurecr.io/yudaback
    container_name: app_back
    volumes:
      - /app/node_modules
      - ./back:/app

    environment:
      - NODE_ENV=production
    env_file:
      - back/.env
    ports:
      - "3002:3002"
    # environment:
    #   - NODE_ENV=production
    #   - POSTGRES_HOST=${POSTGRES_HOST}
    #   - POSTGRES_USERNAME=${POSTGRES_USERNAME}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    #   - POSTGRES_PORT=${POSTGRES_PORT}
    #   - POSTGRES_HOSTPORT=${POSTGRES_HOSTPORT}
      
  # nginx:
  #   restart: always

  #   image: yusushin/docker-nginx

  #   ports:
  #     - "80:80"
