version: '3'

services:
  frontend:
    image: yusu/docker-front

    volumes:
      - /app/node_modules
      - ./front:/app
    
    stdin_open: true

  backend:
    image: yusu/docker-back
    container_name: app_back
    volumes:
      - /app/node_modules
      - ./back:/app
    
  nginx:
    restart: always

    image: yusu/docker-nginx

    ports:
      - "80:80"
