version: '3'

services:
  frontend:
    image: yusushin/docker-front

    volumes:
      - /app/node_modules
      - ./front:/app
    
    stdin_open: true

  backend:
    image: yusushin/docker-back
    container_name: app_back
    volumes:
      - /app/node_modules
      - ./back:/app
    environment:
      POSTGRES_HOST:$HOST
      POSTGRES_USERNAME:$USERNAME
      POSTGRES_PASSWORD:$PASSWORD
      POSTGRES_DATABASE:$DATABASE
      POSTGRES_PORT:$PORT
      POSTGRES_SYNCHRONIZE:false

    
  nginx:
    restart: always

    image: yusushin/docker-nginx

    ports:
      - "80:80"
