name: YuDa CI CD

on:
  push:
    branches:
      - main

env:
  GCE_INSTANCE_NAME: instance-20240617-063334
  GCE_ZONE: us-west1-b

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}      

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: "beta"

    - name: Configure Docker for gcloud
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build --platform=linux/amd64 \
          --build-arg POSTGRES_HOSTPORT="${{ secrets.POSTGRES_HOSTPORT }}" \
          --build-arg POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" \
          --build-arg POSTGRES_PORT="${{ secrets.POSTGRES_PORT }}" \
          --build-arg POSTGRES_USERNAME="${{ secrets.POSTGRES_USERNAME }}" \
          --build-arg POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
          --build-arg POSTGRES_DATABASE="${{ secrets.POSTGRES_DATABASE }}" \
          --build-arg POSTGRES_SYNCHRONIZE="${{ secrets.POSTGRES_SYNCHRONIZE }}" \
          --build-arg JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
          --build-arg JWT_EXPIRES_ACCESS="${{ secrets.JWT_EXPIRES_ACCESS }}" \
          -t yusushin/docker-backend ./back

    - name : tag GCE
      run: docker tag yusushin/docker-backend gcr.io/ardent-medley-426706-t0/yuda-back:${{ github.sha }} \
        
    - name: Push Docker image to Container Registry
      run: docker push gcr.io/ardent-medley-426706-t0/yuda-back:${{ github.sha }} 
    
    - name: Install SSH client
      run: sudo apt-get install -y ssh

    - name: Generate SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
        chmod 644 ~/.ssh/id_rsa.pub

    - name: Set up SSH access
      run: |
        gcloud compute instances add-metadata ${{ env.GCE_INSTANCE_NAME }} \
          --zone ${{ env.GCE_ZONE }} \
          --metadata-from-file ssh-keys=~/.ssh/id_rsa.pub

    - name: Deploy to Cloud Run
      run: |
        gcloud compute ssh --quiet --zone ${{ env.GCE_ZONE }} ${{ env.GCE_INSTANCE_NAME }} \
         --command "docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/yuda-back:${{ github.sha }} && \
         docker run -d -p 80:80 gcr.io/${{ secrets.GCP_PROJECT_ID }}/yuda-back:${{ github.sha }}" \
         --ssh-key-file ~/.ssh/id_rsa

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Get Code 
#       uses: actions/checkout@v3

#     - name: Cache node modules
#       uses: actions/cache@v2
#       with:
#         path: ~/.npm
#         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#         restore-keys: |
#           ${{ runner.os }}-node-
          
#     - name: Login DockerHub
#       run: echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u "${{secrets.DOCKER_HUB_ID}}" --password-stdin 
    
#     - name: login azure
#       run: az login --user "${{secrets.AZURE_LOGIN_ID}}" --password "${{secrets.AZURE_LOGIN_PW}}"

#     # - name: before_install
#     #   run : docker build -t yusushin/yuda -f ./front/Dockerfile.dev ./front

#     # - name: Docker Test
#     #   run : docker run -e CI=true yusushin/yuda npm test 

#     - name: build dockers
#         # docker build --platform=linux/amd64 \
#         #   --build-arg WDS_SOCKET_HOST="${{ secrets.WDS_SOCKET_HOST }}" \
#         #   --build-arg WDS_SOCKET_PATH="${{ secrets.WDS_SOCKET_PATH }}" \
#         #   --build-arg WDS_SOCKET_PORT="${{ secrets.WDS_SOCKET_PORT }}" \
#         #   --build-arg REACT_APP_SERVER="${{ secrets.REACT_APP_SERVER }}" \
#         #   --build-arg REACT_APP_DELAY="${{ secrets.REACT_APP_DELAY }}" \
#         #   -t yusushin/docker-frontend ./front
#       run: |
#         docker build --platform=linux/amd64 \
#           --build-arg POSTGRES_HOSTPORT="${{ secrets.POSTGRES_HOSTPORT }}" \
#           --build-arg POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" \
#           --build-arg POSTGRES_PORT="${{ secrets.POSTGRES_PORT }}" \
#           --build-arg POSTGRES_USERNAME="${{ secrets.POSTGRES_USERNAME }}" \
#           --build-arg POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
#           --build-arg POSTGRES_DATABASE="${{ secrets.POSTGRES_DATABASE }}" \
#           --build-arg POSTGRES_SYNCHRONIZE="${{ secrets.POSTGRES_SYNCHRONIZE }}" \
#           --build-arg JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
#           --build-arg JWT_EXPIRES_ACCESS="${{ secrets.JWT_EXPIRES_ACCESS }}" \
#           -t yusushin/docker-backend ./back

#     - name: authorizate ACR and login to ACR
#       run: | 
#         az acr update -n fronttest --admin-enabled true
#         az acr login --name fronttest

#     - name: clean ACR repository 
#         # az acr repository delete -n fronttest --repository yudafront --yes
#       run: |
#         az acr repository delete -n fronttest --repository yudaback --yes

#     - name: tag ACR name
#         # docker tag yusushin/docker-frontend fronttest.azurecr.io/yudafront:${{ github.sha }} 
#       run: | 
#         docker tag yusushin/docker-backend fronttest.azurecr.io/yudaback:${{ github.sha }} 

#     - name: push the dockers to ACR
#         # docker push fronttest.azurecr.io/yudafront:${{ github.sha }}
#       run: | 
#         docker push fronttest.azurecr.io/yudaback:${{ github.sha }}  
      
#     # - name: Deploy to Azure front Web App
#     #   id: deploy-front-to-webapp
#     #   uses: azure/webapps-deploy@v2
#     #   with:
#     #     app-name: yudafronttest
#     #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#     #     images: 'fronttest.azurecr.io/yudafront:${{ github.sha }}'

#     - name: Deploy to Azure back Web App
#       id: deploy-back-to-webapp
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: yudabacktest
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACK }}
#         images: 'fronttest.azurecr.io/yudaback:${{ github.sha }}'