name: YuDa CI CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get Code 
      uses: actions/checkout@v3

    - name: Login DockerHub
      run: echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u "${{secrets.DOCKER_HUB_ID}}" --password-stdin 
    
    - name: login azure
      run: az login --user "${{secrets.AZURE_LOGIN_ID}}" --password "${{secrets.AZURE_LOGIN_PW}}"

    - name: before_install
      run : docker build -t yusushin/yuda -f ./front/Dockerfile.dev ./front

    - name: Docker Test
      run : docker run -e CI=true yusushin/yuda npm test 

    - name: build dockers
      run: |
        docker build -t yusushin/docker-frontend ./front
        docker build -t yusushin/docker-backend ./back

    - name: authorizate ACR and login to ACR
      run: | 
        az acr update -n fronttest --admin-enabled true
        az acr login --name fronttest

    - name: clean ACR repository 
      run: |
        az acr repository delete -n fronttest --repository yudafront
        az acr repository delete -n fronttest --repository yudaback

    - name: tag ACR name
      run: | 
        docker tag yusushin/docker-frontend fronttest.azurecr.io/yudafront:${{ github.sha }} 
        docker tag yusushin/docker-backend fronttest.azurecr.io/yudaback:${{ github.sha }} 

    - name: push the dockers to ACR
      run: | 
        docker push fronttest.azurecr.io/yudafront:${{ github.sha }}
        docker push fronttest.azurecr.io/yudaback:${{ github.sha }}  
      
    - name: Deploy to Azure front Web App
      id: deploy-front-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: yudafronttest
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'fronttest.azurecr.io/yudafront:${{ github.sha }}'

    - name: Deploy to Azure back Web App
      id: deploy-back-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: yudabacktest
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACK }}
        images: 'fronttest.azurecr.io/yudaback:${{ github.sha }}'